### ISSUE TITLE
Depreciation Warning in Python 3.8

### ISSUE THREAD

**Issue by NickWaterton** [keans/pushno#1]
I get this warning:
```
/usr/local/lib/python3.8/dist-packages/pushno/plugins/prowl.py:33: DeprecationWarning:This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
```

**Comment by keans** [comment]
Yes, thanks for the hint. It seems that starting from 3.9 this method got even been removed. Documentation says: `Deprecated since version 3.2, will be removed in version 3.9: Use list(elem) or iteration.`

Anyways, I have fixed it, so please upgrade to the new version 0.0.3.
